apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuber-ingress-35
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /order
          pathType: Prefix
          backend:
            service:
              name: kuber-dp-order-35
              port:
                number: 80
        - path: /account
          pathType: Prefix
          backend:
            service:
              name: kuber-dp-billing-35
              port:
                number: 80
        - path: /notification
          pathType: Prefix
          backend:
            service:
              name: kuber-dp-notification-35
              port:
                number: 80
